### ISSUE TITLE
how can i free the goroutine

### ISSUE THREAD

**Issue by letitbezh** [deckarep/golang-set#104]
I have use this program in my code，but this cost too many goroutines，how can i solve it
![image](https://user-images.githubusercontent.com/15907176/184677938-c406c50e-0acd-4836-ae55-1da7d2a01e94.png)

**Comment by deckarep** [comment]
Hello,

The set implementation has two APIs for iteration with `Iter` being one and `Each` being the other.

The `Iter` api has a design flaw where you may leak goroutines if you early-return without finishing the consume of it.

The `Each` does not have this problem. Alternatively you can still use `Iter` as long as you make sure to iterate completely without stopping early.

**Comment by letitbezh** [comment]
Thanks for your answer。 i will try to fix my problem

**Comment by letitbezh** [comment]
Thanks for your answer, i have fixed my problem
