### ISSUE TITLE
Missing support Len()/Count()/Size() method?

### ISSUE THREAD

**Issue by jordaniversen** [deckarep/golang-set#105]
Is this intentional or am I missing it?

Thank you

**Comment by nikist97** [comment]
I am not a maintainer, but from my experience with the package I believe you are looking for `Cardinality()`

**Comment by jordaniversen** [comment]
I just stumbled on that as well, thanks @nikist97.

Closing this as per https://github.com/deckarep/golang-set/blob/main/set.go#L47
