### ISSUE TITLE
iterate with random sequence?

### ISSUE THREAD

**Issue by ZhengQiushi** [deckarep/golang-set#107]
`	it := join_seq.Iterator()
	for elem := range it.C {
         }`

Following your document, I use the iterator to scan the set, but the result will be random... and is not the fixed sequence in data.s

**Comment by deckarep** [comment]
If I understand your question, order is not guaranteed when iterating the sets. 

The primary reason is because the implementation is backed by a map and Go map’s don’t provide any guaranteed order when iterating over the key/values.
