### ISSUE TITLE
Getting error when instantiating a set: "invalid operation: cannot index mapset.NewSet (value of type func(s ...interface{}) mapset.Set)"

### ISSUE THREAD

**Issue by pcgeek86** [deckarep/golang-set#111]
* Golang 1.20
* MacOS
* VSCode

### Repro Steps

```
myset := mapset.NewSet[string]()
```

### Actual Result 

> invalid operation: cannot index mapset.NewSet (value of type func(s ...interface{}) mapset.Set)

### Expected Result

New set should be instantiated.

**Comment by deckarep** [comment]
@pcgeek86 - Hi, this is pretty surprising if this is somehow broken on Go 1.20 and I'll be investigating this today. In the meantime, if anyone else experiences this with 1.20 please +1 this issue.

**Comment by pcgeek86** [comment]
Thanks, I'm pretty new to Go. I was just copying the example from the README, and was surprised that it was throwing the error.

**Comment by deckarep** [comment]
So far I can't reproduce the issue you are seeing...here is a complete code snippet running `go1.20`

```go
package main

import (
	"fmt"
	mapset "github.com/deckarep/golang-set/v2"
	"runtime"
)

func main() {
	// Create a string-based set of required classes.
	req := mapset.NewSet[string]()
	req.Add("cooking")
	req.Add("english")
	req.Add("math")
	req.Add("biology")

	fmt.Printf("Go version: %s\n", runtime.Version())
	fmt.Println("size: ", req.Cardinality())

	req.Each(func(x string) bool {
		fmt.Println("->", x)
		return false
	})
}
```

**Comment by deckarep** [comment]
You mentioned you are new to Go, a couple of things to make sure:

1. That you are properly importing the correct version of the Set `v2`
2. That you are using Go modules correctly which is the recommended way to use dependencies for awhile now: `go get github.com/deckarep/golang-set/v2`
3. That your Go environment is properly setup, perhaps try pulling in other dependencies to make sure things are solid.

**Comment by pcgeek86** [comment]
I just created a new folder / module and was able to repro the issue.

```
> go mod init trevortest
> go get github.com/deckarep/golang-set
```

<img width="868" alt="Screenshot 2023-03-05 at 11 49 00 AM" src="https://user-images.githubusercontent.com/466713/222979829-31aa4ec6-d8f7-4068-b38e-dce8598944eb.png">

<img width="704" alt="Screenshot 2023-03-05 at 11 49 52 AM" src="https://user-images.githubusercontent.com/466713/222979850-e5ebee01-ef43-4920-84e9-af8c17a3c14a.png">

### Go.mod

<img width="724" alt="Screenshot 2023-03-05 at 11 50 11 AM" src="https://user-images.githubusercontent.com/466713/222979861-83f1944e-6744-4d83-920a-0d4293c76d23.png">

**NOTE**: I solved the issue by appending `/v2` to the module name. Thanks for pointing that out! I had incorrectly assumed the module name was just the GitHub repo path.

**Comment by deckarep** [comment]
Glad it's resolved!
