### ISSUE TITLE
Is there any method to know whether a set is empty?

### ISSUE THREAD

**Issue by Derick317** [deckarep/golang-set#132]
Is there any method to know whether a set is empty? Or is there any method to get the number of elements in a set?

**Comment by deckarep** [comment]
Hi @Derick317,

Actually the closest thing is to check Cardinality with 0 but this is such a common thing to do that I think it’s worth adding a dedicated method for this.

An IsEmpty method should probably be added. I can do this or if you are more than welcome to.

**Comment by deckarep** [comment]
Closing as this was completed by @Jibaru - Thank You!
And Thank You @Derick317 for the suggestion!
