### ISSUE TITLE
why isn't there a `mapset.NewSetFromSlice` method?

### ISSUE THREAD

**Issue by ibukunoluwayomi** [deckarep/golang-set#137]
Just like `mapset.NewSetFromMapKeys()` which is very handy. I think `mapset.NewSetFromSlice` will be quite helpful

**Comment by deckarep** [comment]
Hello,

I believe we used to have such methods but they've been streamlines by having some of the New* functions be variadic which means you can still pass a slice in and would just need to expand it with the .. syntax.

Let me know if that is what you're looking for.

Thanks,

-Deckarep
