### ISSUE TITLE
HashiCorp uses own set package

### ISSUE THREAD

**Issue by guettli** [deckarep/golang-set#144]
On the Github page you say that HashiCorp trust this package.

A saw that HashiCorp have their own set package now:

https://pkg.go.dev/github.com/hashicorp/go-set/v3

Maybe HashiCorp should get removed from the list?

**Comment by deckarep** [comment]
Looks like Consul is still using this version: https://github.com/hashicorp/consul/blob/3e6f1c1fe104081681bcec800d30aea9bd71ce80/go.mod#L28
