### ISSUE TITLE
Change thread-safety to use a decorator pattern

### ISSUE THREAD

**Issue by rickb777** [deckarep/golang-set#21]
First of all, this suggestion would be a breaking change.

You could separate your concerns better if you implemented the thread-safe mutex code as a decorator for another `Set`. Then your core implementation would only need the thread-unsafe version. A new a `mapset.ThreadSafe(Set)` function would be added to the API.

The two advantages are

* other `Set` implementations outside of yours need only provide a thread-unsafe implementation. The mutex decorator I am proposing would make it easy to get thread-safe versions of any implementation.

* your API could be simplified because `mapset.NewSet()` and `mapset.NewSetFromSlice([]interface)` functions would normally return the **thread-unsafe** flavour and the new `mapset.ThreadSafe(Set)` function would be used to wrap the result.

There would be a tiny performance reduction, but the greater clarity and generality would be worth it.

**Comment by sleaze** [comment]
Thumbs down.

"Let's break everything" - This seems like a _TERRIBLE_ idea!
