### ISSUE TITLE
add MarshalJSON / UnmarshalJSON  

### ISSUE THREAD

**Issue by sclasen** [deckarep/golang-set#24]
would be nice to be able to serialize to a json array and back.

**Comment by deckarep** [comment]
@sclasen - can you provide more details of what you are looking for?  The set's backing structure is not an array so not sure what you mean exactly.

**Comment by sclasen** [comment]
Yeah thats what I mean, basically not exposing the underlying structure in serialization.

Closest thing you can get is a json array I think.

Currently serializing one of these sets to json would look something like

```json
{"aSet": {"s": {"aMember": "", "anotherMember" : "", "aThirdMember": ""}}
```

where something like this would be much easier to consume

```json
{"aSet": ["aMember", "anotherMember", "aThirdMember"]}
```

Not postive this is actually possible with go encoding/json thought....

**Comment by sclasen** [comment]
or actually since the threadunsafe set is private, it wouldnt get serialized at all.

**Comment by thorhs** [comment]
I have a simple MarshalJSON implemented, basically just a ToSlice wrapped in json.Marshal.  Does the trick for me, but then again, I don't need the Unmarshal:

```go
func (set *threadUnsafeSet) MarshalJSON() ([]byte, error) {
        items := set.ToSlice()

        return json.Marshal(items)
}
```

Feel free to use this if you feel so inclined.

**Comment by suntong** [comment]
+1, 

I need serializing these sets to json as well. 

If @thorhs and @Aorioli's patch is good, please merge it. 

Thanks
