### ISSUE TITLE
If Iter half, then break, memory leak? 

### ISSUE THREAD

**Issue by yalay** [deckarep/golang-set#33]
example：
```
for v := range s.Iter() {
    if v, ok := v.(int); ok {
        if v == definedValue {
            break
        }
    }
}
```

the channel Iter() returned will be never closed?

**Comment by deckarep** [comment]
Yes, this is a problem that needs to be adressed.  There is another open PR I still need to review that attempts to fix this with a Stoppable Iterator.

**Comment by yalay** [comment]
### one Solution
```
func (set *threadUnsafeSet) Iter() <-chan interface{} {
    ch := make(chan interface{}, set.Cardinality())
    for elem := range *set {
        ch <- elem
    }
    close(ch)
    return ch
}
```
A closed channel can be read,but occupy another memory of the set.

**Comment by deckarep** [comment]
This has since been resolved with the following PR: https://github.com/deckarep/golang-set/pull/32
