### ISSUE TITLE
Tag a new release (1.6?)

### ISSUE THREAD

**Issue by chancez** [deckarep/golang-set#42]
@deckarep Would you be willing to tag another release with what's on master? Theres been a fix to a deadlock and a few new features since the 1.5 release, so now would be a decent time to do a 1.6.

It would help me a lot since it would mean less random git sha's in my glide.yaml, and would make it easier for me to determine if/when a new release might be available automatically.

**Comment by deckarep** [comment]
@chancez - yes this has been on my mind as something I need to do.  Thanks for the friendly reminder.

**Comment by deckarep** [comment]
Done!
