### ISSUE TITLE
Document the complexity of operations

### ISSUE THREAD

**Issue by sheerun** [deckarep/golang-set#48]
Hey,

I wanted to use your package and started to read documentation, but I couldn't find the complexity of operations on it. From my previous experience the access operation (Contains) should take O(log(n)) by using something like radix index. Instead it turned out O(n) as it seems you just iterate through all items.

Could you please document in the readme approximate cost of each operation? Thank you!

**Comment by deckarep** [comment]
It is not O(n), it is only iterating through the arguments you are checking.  If you look at the implementation it's doing a direct lookup using a map. This means if you do a Contains of one argument, you'll generally get the same exact runtime complexity as a map. Perhaps either O(1) or O(log n) for more complicated work loads.

**Comment by deckarep** [comment]
Documenting the runtime is a good idea but it's not something I have time to fully sit down and analyze but I'd welcome a PR. 

These implementations are backed by maps so in general you will observe similar performance characteristics. In the more complex operations I've insured to take the obvious optimizations so as to cut down on unnecessary work.
