### ISSUE TITLE
Iterator with go routine

### ISSUE THREAD

**Issue by shridharmanvi** [deckarep/golang-set#49]
Hey, I am trying to use elements of a set individually on different go routines using Iterator. But facing a weird issue. When using a go routine for each element, the value duplicates (or skips a value?). Have a look at the example below:
``` go
package main

import (
	"fmt"
	"github.com/deckarep/golang-set"
)

func main() {

	set := mapset.NewSet()

	set.Add("one")
	set.Add("two")
	set.Add("three")
	set.Add("three")
	set.Add("four")
	set.Add("five")
	set.Add("five")

	fmt.Println(set)

	iterator := set.Iterator()

	fmt.Println("\nIndividual elements are:")
	for ele := range iterator.C {
		go func() {
			fmt.Println(ele)
		}()
	}
}
```

The output looks like this:
```
Set{one, two, three, four, five}

Individual elements are:
two
two
four
five
```

I do see the set has unique elements in it. But on iterating and reading elements on different goroutines, it does not work as expected. Elements one, three are missing and two appears twice.

Am I missing something? Or using go routines inappropriately? 

Thanks

**Comment by sabhiram** [comment]
Perhaps two ... 
1. The for-loop will return and exit your program before all the `go func`s have a chance to run
2. You probably should pass ele into the inner `go func`
