### ISSUE TITLE
Someone said this function (mapset.Iter) has bug, but I don't know where is it. Plz tell me

### ISSUE THREAD

**Issue by gravitywp** [deckarep/golang-set#50]
The interview question url is:https://zhuanlan.zhihu.com/p/26972862 
The title is 9、下面的迭代会有什么问题？

Your code url is :
https://github.com/deckarep/golang-set/blob/master/threadsafe.go#L154

I think that code is right, no bug. So what you opinion?

**Comment by dayuoba** [comment]
if someone outside, has the returned channel and he does not consume all the channel msgs, the lock has the potential of being a deaded lock

**Comment by gitbufenshuo** [comment]
- 没有停止机制

- 我就不明白了，一个【小写】的结构体拥有一个【大写】的方法这种事情就这么好玩？【应该尽量不这么写，🙃😆】

**Comment by andy-zhangtao** [comment]
I think we should analysis code with application context. Simply looks this function seems right, no bug here.

**Comment by deckarep** [comment]
Yes it is a bug where if you don't fully consume from the channel and break early, you will experience a leaked goroutine.

This is why there is another function called Iterator which allows you to signal that you're done early when iterating and notify the channel.

The better solution which is on my list is to have Iterator take a cancelable Context which is the better pattern for this type of scenario.

I'll be implementing it soon.

**Comment by deckarep** [comment]
Here is the related thread: https://github.com/deckarep/golang-set/issues/33

**Comment by lkiversonlk** [comment]
BTW, it's not the common usage pattern of Iterator

**Comment by gravitywp** [comment]
@deckarep Thanks for your reply. Seem to be the right answer to me. Should I close the issue?

**Comment by deckarep** [comment]
Sure

thanks!
