### ISSUE TITLE
Map pointers in implementation of threadUnsafeSet()

### ISSUE THREAD

**Issue by dgiridharan** [deckarep/golang-set#54]
NOTE: I'm new to golang, so please ignore this if you think this issue/suggestion isn't relevant. If it's not relevant, please ignore this and sorry for the trouble.

Example:
func (set *threadUnsafeSet) Add(i interface{}) bool

Aren't Maps reference types, so aren't they allways passed by reference?

What's the difference between using:
func (set threadUnsafeSet) Add(i interface{}) bool

**Comment by deckarep** [comment]
Hi -- yes you're right that maps are reference types and copying them is
cheap and does not copy the underlying contents.

But for your question the API takes a pointer to be consistent and in line
with how the threadsafe version works. This way when you use the Set
structures whether you use a threadsafe version or not you just hold a
reference to a pointer in both cases.

So we end up doing a little extra dereferencing on your behalf for a
cleaner and more consistent API.

Cheers!

**Comment by dgiridharan** [comment]
Thanks for the explanation!
