### ISSUE TITLE
Set map capacity for some functions can improve performance

### ISSUE THREAD

**Issue by fy0** [deckarep/golang-set#60]
Recently I use golang-set to help optimize a DFA generator.

And I noticed DFA‘s compile time increased a lot.

New code:
![image](https://user-images.githubusercontent.com/1579850/43064265-fe6a2748-8e90-11e8-97bc-d2a3f7670b22.png)

Before:
![image](https://user-images.githubusercontent.com/1579850/43053710-b5bf93f0-8e60-11e8-9b69-21c824b6b6ec.png)

After:
![image](https://user-images.githubusercontent.com/1579850/43064382-568685e8-8e91-11e8-8ceb-bc7403f0edbe.png)

pprof:
![image](https://user-images.githubusercontent.com/1579850/43064445-7c8edc40-8e91-11e8-90d9-e2a673d46829.png)

`golang-set` based on map. I guess frequently insert caused rehashes and memory copies.

I tried to reuse nextKeys and failNext, but nothing happened. I found this from golang-set's code:

![image](https://user-images.githubusercontent.com/1579850/43054121-a3f83396-8e62-11e8-89c0-59a93b4aa195.png)

Every time I clear the set, a new one created to replace the old one.

As we know, golang never reclaim memory from alive maps, so I use a for loop to remove all items from set instead of another create. But, new clear is more slower than before because remove loop takes more time.

I wrote a new clear function to reduce realloc of map:
![image](https://user-images.githubusercontent.com/1579850/43066382-188bf24a-8e97-11e8-9c5a-4954d781e7de.png)

![image](https://user-images.githubusercontent.com/1579850/43066591-a50b010c-8e97-11e8-993d-f1d25456cc08.png)

![image](https://user-images.githubusercontent.com/1579850/43066606-b1cb83c6-8e97-11e8-9e65-fa499315daa6.png)

This Time, results are better than before:
![image](https://user-images.githubusercontent.com/1579850/43066669-db4e9bde-8e97-11e8-9d85-9fa1e15f396e.png)

![image](https://user-images.githubusercontent.com/1579850/43066712-f606c208-8e97-11e8-89f3-1da2d5617425.png)

Saved about 1s, `add` function of set still takes biggest part of times. I suppose 2~3s will be saved if we set a proper capacity for `Difference`, `Intersect`, `Union`, etc.

P.S. The conclusion of first version is wrong, I'm sorry for my fault.

**Comment by deckarep** [comment]
So what modifications to the API are you proposing ultimately?

Your usecase seems to be somewhat specific and maintaining backwards compatibility is important.

Your analysis is detailed but it’s still not entirely clear to me what you want changed?

Would you like to submit a PR? We can review the code together.

**Comment by fy0** [comment]
@deckarep If a function create a new mapset based on old mapsets, specify a size can improve performance.

**Comment by deckarep** [comment]
Okay, I will look at adding these optimizations...in the meantime if you want to submit a PR to get this done faster that would be super helpful!

Thanks!

**Comment by OLPMO** [comment]
@deckarep Has this improvement been mergeed into the release ?

**Comment by deckarep** [comment]
@OLPMO - not yet it’s sitting in PR #63. Would you like to review the changes and let me know how it looks?

**Comment by deckarep** [comment]
@fy0 - closing this as the proposed work has finally been merged.
