### ISSUE TITLE
ToSlice() from string slice returns numbers

### ISSUE THREAD

**Issue by maginemu** [deckarep/golang-set#65]
Simple example

```
s := mapset.NewSetFromSlice([]interface{}{"foo", "bar", "baz"})

fmt.Println(s)

for item := range s.ToSlice() {
    fmt.Println(item)
}
```

produces below:
```
Set{foo, bar, baz}
0
1
2
```

Is this designed behavior?

I expected below:
```
Set{foo, bar, baz}
foo
bar
baz
```

(I found I could use s.Iter() to produce expected output though)

**Comment by deckarep** [comment]
Hello,

You are seeing numbers because your `for` loop is incorrect.  In Go, `for` loops that use the range keyword supply an index value only. If you want the actual value you need to write it like the following:

```
for _, item := range s.ToSlice(){
  fmt.Println(item)
}
```

**Comment by maginemu** [comment]
Hello, thank you for your kind reply.  I got it.
