### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [deckarep/golang-set#67]
I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, projects could parse out the address and provide donation capabilities to the user.

**Comment by deckarep** [comment]
I'm not entirely sure I have enough context on the purpose of this request. This library is in fact used in Ethereum but currently is not associated with Ethereum or maintained by the Ethereum organization and/or community.
