### ISSUE TITLE
Feature Request: TOML Serialization

### ISSUE THREAD

**Issue by ameyer-pivotal** [deckarep/golang-set#68]
It would be really valuable if this set type implemented the [BurntSushi `TextUnmarshaler` interface](https://github.com/BurntSushi/toml#using-the-encodingtextunmarshaler-interface), so it can be used with that library without needing to wrap the set (or fork the repo)

**Comment by deckarep** [comment]
I wouldn't be opposed to adding this to this library but I would like to flag this as a good candidate as a community contribution patch and would welcome anyone wanting to tackle it.

Thanks for the submission.

**Comment by ameyer-pivotal** [comment]
Sounds good! I'll be doing it on a fork, so when I have time to make it merge-worthy, I can PR it in :)

**Comment by deckarep** [comment]
Closing because I no longer think serialization formats should be a part of this package.
