### ISSUE TITLE
Why does `NewSet()` take optional elements but `NewThreadUnsafeSet()` doesn't?

### ISSUE THREAD

**Issue by jeffwidman** [deckarep/golang-set#80]
It's weird that `NewThreadUnsafeSet()` doesn't take optional elements and includes them in the returned set.

The ergonomics of `NewSet(... interface{})` are much nicer!

Also, the docs for `NewSet()` say it returns an empty set, yet that's not necessarily true... I was going to open a PR to fix that when I noticed the inconsistency with `NewThreadUnsafeSet()`. 

So would you rather they both take optional args, or neither?

IMO the former is both backwards compatible and also a more pleasant API.

**Comment by deckarep** [comment]
Thanks for the input! 

I would prefer the former to preserver backwards compatibility and a nicer API experience. Feel free to submit a patch against the generics branch that drops into main soon! I'll start taking changes on that branch moving forward.

**Comment by jeffwidman** [comment]
See both #83 and then that unlocks #84...
