### ISSUE TITLE
Please update the examples!

### ISSUE THREAD

**Issue by Anangaya** [deckarep/golang-set#98]
I'm not sure if it's just me, but nothing worked for me (not even the examples!) after the new update.
![Code_fWgCmd3Rs9](https://user-images.githubusercontent.com/73894038/170719223-16dea888-8a62-48e2-bde3-f3d644679717.png)

If the examples are broken please fix them.

**Comment by SennayT** [comment]
I had the same problem, import as
```
import (
	mapset "github.com/deckarep/golang-set/v2"
)
```

In go.mod update golang-set to version 2xx (as of writing it is at 2.1.0)
```
require github.com/deckarep/golang-set/v2 v2.1.0
```
I think the import in the documentation is for version 1

**Comment by deckarep** [comment]
Sorry about this, I have updated the readme with the relevant import fixed. Please let me know if that addresses this issue and feel free to re-open.
